/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceEntry {
  'status' : AttendanceStatus,
  'studentId' : string,
  'note' : [] | [string],
}
export interface AttendanceRecord {
  'id' : string,
  'status' : AttendanceStatus,
  'studentId' : string,
  'date' : string,
  'note' : [] | [string],
  'classId' : string,
  'markedBy' : Principal,
}
export type AttendanceStatus = { 'Present' : null } |
  { 'Absent' : null };
export interface Class {
  'id' : string,
  'subject' : string,
  'name' : string,
  'createdAt' : bigint,
  'section' : string,
  'teacherId' : Principal,
}
export interface ClassAttendanceStat {
  'totalStudents' : bigint,
  'classId' : string,
  'attendancePercent' : number,
  'className' : string,
}
export interface ClassInput {
  'subject' : string,
  'name' : string,
  'section' : string,
}
export interface ClassReport {
  'endDate' : string,
  'classId' : string,
  'dailyStats' : Array<DailyClassStat>,
  'startDate' : string,
}
export interface DailyClassStat {
  'date' : string,
  'presentCount' : bigint,
  'attendancePercent' : number,
  'absentCount' : bigint,
}
export interface DashboardStats {
  'totalStudents' : bigint,
  'weeklyTrend' : Array<WeeklyTrendPoint>,
  'recentAbsences' : Array<RecentAbsence>,
  'todayClassStats' : Array<ClassAttendanceStat>,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface NotificationLog {
  'id' : string,
  'parentEmail' : string,
  'studentId' : string,
  'sentAt' : bigint,
  'sentBy' : Principal,
  'message' : string,
}
export interface RecentAbsence {
  'studentId' : string,
  'studentName' : string,
  'date' : string,
  'classId' : string,
  'className' : string,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface SendNotificationResult {
  'logged' : boolean,
  'emailSent' : boolean,
}
export interface Student {
  'id' : string,
  'parentEmail' : string,
  'name' : string,
  'createdAt' : bigint,
  'classId' : string,
  'rollNumber' : string,
}
export interface StudentInput {
  'parentEmail' : string,
  'name' : string,
  'classId' : string,
  'rollNumber' : string,
}
export interface StudentReport {
  'studentId' : string,
  'endDate' : string,
  'daysAbsent' : bigint,
  'daysPresent' : bigint,
  'attendancePercent' : number,
  'startDate' : string,
}
export interface Teacher {
  'id' : Principal,
  'school' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
}
export interface TeacherInput {
  'school' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyTrendPoint { 'overallPercent' : number, 'date' : string }
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClass' : ActorMethod<[ClassInput], Class>,
  'createTeacherProfile' : ActorMethod<[TeacherInput], Teacher>,
  'deleteClass' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'editAttendanceRecord' : ActorMethod<
    [string, AttendanceStatus, [] | [string]],
    AttendanceRecord
  >,
  'generateClassReport' : ActorMethod<[string, string, string], ClassReport>,
  'generateStudentReport' : ActorMethod<
    [string, string, string],
    StudentReport
  >,
  'getAttendanceByClassAndDate' : ActorMethod<
    [string, string],
    Array<AttendanceRecord>
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClass' : ActorMethod<[string], [] | [Class]>,
  'getClassStudents' : ActorMethod<[string], Array<Student>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyClasses' : ActorMethod<[], Array<Class>>,
  'getNotificationLog' : ActorMethod<[string], Array<NotificationLog>>,
  'getStudent' : ActorMethod<[string], [] | [Student]>,
  'getStudentAttendance' : ActorMethod<
    [string, string, string],
    Array<AttendanceRecord>
  >,
  'getTeacherProfile' : ActorMethod<[], [] | [Teacher]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<
    [string, string, Array<AttendanceEntry>],
    Array<AttendanceRecord>
  >,
  'registerStudent' : ActorMethod<[StudentInput], Student>,
  'sendParentNotification' : ActorMethod<
    [string, string],
    SendNotificationResult
  >,
  'updateClass' : ActorMethod<[string, ClassInput], Class>,
  'updateStudent' : ActorMethod<[string, StudentInput], Student>,
  'updateTeacherProfile' : ActorMethod<[TeacherInput], Teacher>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];