/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuizQuestion = IDL.Record({
  'answerOptions' : IDL.Vec(IDL.Text),
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CourseInput = IDL.Record({
  'difficultyLevel' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'instructorName' : IDL.Text,
});
export const LessonInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'videoUrl' : IDL.Text,
  'courseId' : IDL.Nat,
  'orderIndex' : IDL.Nat,
});
export const EnrollmentInput = IDL.Record({ 'courseId' : IDL.Nat });
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'difficultyLevel' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'lessonIds' : IDL.Vec(IDL.Nat),
  'durationMinutes' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'instructorName' : IDL.Text,
});
export const Review = IDL.Record({
  'reviewText' : IDL.Text,
  'student' : IDL.Principal,
  'rating' : IDL.Nat,
  'courseId' : IDL.Nat,
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'videoUrl' : IDL.Text,
  'courseId' : IDL.Nat,
  'orderIndex' : IDL.Nat,
});
export const Time = IDL.Int;
export const Enrollment = IDL.Record({
  'completionPercentage' : IDL.Nat,
  'completedLessons' : IDL.Vec(IDL.Nat),
  'student' : IDL.Principal,
  'enrollmentDate' : Time,
  'courseId' : IDL.Nat,
});
export const QuizSubmission = IDL.Record({
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'student' : IDL.Principal,
  'courseId' : IDL.Nat,
});
export const QuizSubmissionInput = IDL.Record({
  'answers' : IDL.Vec(IDL.Nat),
  'courseId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuizQuestions' : IDL.Func([IDL.Nat, IDL.Vec(QuizQuestion)], [], []),
  'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCourse' : IDL.Func([CourseInput], [IDL.Nat], []),
  'createLesson' : IDL.Func([LessonInput], [IDL.Nat], []),
  'enrollInCourse' : IDL.Func([EnrollmentInput], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [Course], ['query']),
  'getCourseReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getCoursesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
  'getCoursesSortedByPrice' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getLesson' : IDL.Func([IDL.Nat], [Lesson], ['query']),
  'getMyEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getMyQuizResults' : IDL.Func([], [IDL.Vec(QuizSubmission)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markLessonComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'submitQuiz' : IDL.Func([QuizSubmissionInput], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuizQuestion = IDL.Record({
    'answerOptions' : IDL.Vec(IDL.Text),
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CourseInput = IDL.Record({
    'difficultyLevel' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'instructorName' : IDL.Text,
  });
  const LessonInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'videoUrl' : IDL.Text,
    'courseId' : IDL.Nat,
    'orderIndex' : IDL.Nat,
  });
  const EnrollmentInput = IDL.Record({ 'courseId' : IDL.Nat });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'difficultyLevel' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'lessonIds' : IDL.Vec(IDL.Nat),
    'durationMinutes' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'instructorName' : IDL.Text,
  });
  const Review = IDL.Record({
    'reviewText' : IDL.Text,
    'student' : IDL.Principal,
    'rating' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'videoUrl' : IDL.Text,
    'courseId' : IDL.Nat,
    'orderIndex' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Enrollment = IDL.Record({
    'completionPercentage' : IDL.Nat,
    'completedLessons' : IDL.Vec(IDL.Nat),
    'student' : IDL.Principal,
    'enrollmentDate' : Time,
    'courseId' : IDL.Nat,
  });
  const QuizSubmission = IDL.Record({
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'student' : IDL.Principal,
    'courseId' : IDL.Nat,
  });
  const QuizSubmissionInput = IDL.Record({
    'answers' : IDL.Vec(IDL.Nat),
    'courseId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuizQuestions' : IDL.Func([IDL.Nat, IDL.Vec(QuizQuestion)], [], []),
    'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCourse' : IDL.Func([CourseInput], [IDL.Nat], []),
    'createLesson' : IDL.Func([LessonInput], [IDL.Nat], []),
    'enrollInCourse' : IDL.Func([EnrollmentInput], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Nat], [Course], ['query']),
    'getCourseReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getCoursesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
    'getCoursesSortedByPrice' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getLesson' : IDL.Func([IDL.Nat], [Lesson], ['query']),
    'getMyEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getMyQuizResults' : IDL.Func([], [IDL.Vec(QuizSubmission)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markLessonComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'submitQuiz' : IDL.Func([QuizSubmissionInput], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };