/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : bigint,
  'difficultyLevel' : string,
  'title' : string,
  'thumbnailUrl' : string,
  'tags' : Array<string>,
  'description' : string,
  'lessonIds' : Array<bigint>,
  'durationMinutes' : bigint,
  'category' : string,
  'price' : bigint,
  'instructorName' : string,
}
export interface CourseInput {
  'difficultyLevel' : string,
  'title' : string,
  'thumbnailUrl' : string,
  'tags' : Array<string>,
  'description' : string,
  'durationMinutes' : bigint,
  'category' : string,
  'price' : bigint,
  'instructorName' : string,
}
export interface Enrollment {
  'completionPercentage' : bigint,
  'completedLessons' : Array<bigint>,
  'student' : Principal,
  'enrollmentDate' : Time,
  'courseId' : bigint,
}
export interface EnrollmentInput { 'courseId' : bigint }
export interface Lesson {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'durationMinutes' : bigint,
  'videoUrl' : string,
  'courseId' : bigint,
  'orderIndex' : bigint,
}
export interface LessonInput {
  'title' : string,
  'description' : string,
  'durationMinutes' : bigint,
  'videoUrl' : string,
  'courseId' : bigint,
  'orderIndex' : bigint,
}
export interface QuizQuestion {
  'answerOptions' : Array<string>,
  'questionText' : string,
  'correctAnswerIndex' : bigint,
}
export interface QuizSubmission {
  'answers' : Array<bigint>,
  'score' : bigint,
  'student' : Principal,
  'courseId' : bigint,
}
export interface QuizSubmissionInput {
  'answers' : Array<bigint>,
  'courseId' : bigint,
}
export interface Review {
  'reviewText' : string,
  'student' : Principal,
  'rating' : bigint,
  'courseId' : bigint,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuizQuestions' : ActorMethod<[bigint, Array<QuizQuestion>], undefined>,
  'addReview' : ActorMethod<[bigint, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<[CourseInput], bigint>,
  'createLesson' : ActorMethod<[LessonInput], bigint>,
  'enrollInCourse' : ActorMethod<[EnrollmentInput], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[bigint], Course>,
  'getCourseReviews' : ActorMethod<[bigint], Array<Review>>,
  'getCoursesByCategory' : ActorMethod<[string], Array<Course>>,
  'getCoursesSortedByPrice' : ActorMethod<[], Array<Course>>,
  'getLesson' : ActorMethod<[bigint], Lesson>,
  'getMyEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'getMyQuizResults' : ActorMethod<[], Array<QuizSubmission>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markLessonComplete' : ActorMethod<[bigint, bigint], undefined>,
  'submitQuiz' : ActorMethod<[QuizSubmissionInput], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];