/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClassInput = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
});
export const Class = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'section' : IDL.Text,
  'teacherId' : IDL.Principal,
});
export const TeacherInput = IDL.Record({
  'school' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : IDL.Principal,
  'school' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
});
export const AttendanceStatus = IDL.Variant({
  'Present' : IDL.Null,
  'Absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : AttendanceStatus,
  'studentId' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'classId' : IDL.Text,
  'markedBy' : IDL.Principal,
});
export const DailyClassStat = IDL.Record({
  'date' : IDL.Text,
  'presentCount' : IDL.Nat,
  'attendancePercent' : IDL.Float64,
  'absentCount' : IDL.Nat,
});
export const ClassReport = IDL.Record({
  'endDate' : IDL.Text,
  'classId' : IDL.Text,
  'dailyStats' : IDL.Vec(DailyClassStat),
  'startDate' : IDL.Text,
});
export const StudentReport = IDL.Record({
  'studentId' : IDL.Text,
  'endDate' : IDL.Text,
  'daysAbsent' : IDL.Nat,
  'daysPresent' : IDL.Nat,
  'attendancePercent' : IDL.Float64,
  'startDate' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Text,
  'parentEmail' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'classId' : IDL.Text,
  'rollNumber' : IDL.Text,
});
export const WeeklyTrendPoint = IDL.Record({
  'overallPercent' : IDL.Float64,
  'date' : IDL.Text,
});
export const RecentAbsence = IDL.Record({
  'studentId' : IDL.Text,
  'studentName' : IDL.Text,
  'date' : IDL.Text,
  'classId' : IDL.Text,
  'className' : IDL.Text,
});
export const ClassAttendanceStat = IDL.Record({
  'totalStudents' : IDL.Nat,
  'classId' : IDL.Text,
  'attendancePercent' : IDL.Float64,
  'className' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalStudents' : IDL.Nat,
  'weeklyTrend' : IDL.Vec(WeeklyTrendPoint),
  'recentAbsences' : IDL.Vec(RecentAbsence),
  'todayClassStats' : IDL.Vec(ClassAttendanceStat),
});
export const NotificationLog = IDL.Record({
  'id' : IDL.Text,
  'parentEmail' : IDL.Text,
  'studentId' : IDL.Text,
  'sentAt' : IDL.Int,
  'sentBy' : IDL.Principal,
  'message' : IDL.Text,
});
export const AttendanceEntry = IDL.Record({
  'status' : AttendanceStatus,
  'studentId' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
});
export const StudentInput = IDL.Record({
  'parentEmail' : IDL.Text,
  'name' : IDL.Text,
  'classId' : IDL.Text,
  'rollNumber' : IDL.Text,
});
export const SendNotificationResult = IDL.Record({
  'logged' : IDL.Bool,
  'emailSent' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClass' : IDL.Func([ClassInput], [Class], []),
  'createTeacherProfile' : IDL.Func([TeacherInput], [Teacher], []),
  'deleteClass' : IDL.Func([IDL.Text], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'editAttendanceRecord' : IDL.Func(
      [IDL.Text, AttendanceStatus, IDL.Opt(IDL.Text)],
      [AttendanceRecord],
      [],
    ),
  'generateClassReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ClassReport],
      ['query'],
    ),
  'generateStudentReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [StudentReport],
      ['query'],
    ),
  'getAttendanceByClassAndDate' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([IDL.Text], [IDL.Opt(Class)], ['query']),
  'getClassStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMyClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getNotificationLog' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NotificationLog)],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'getStudentAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getTeacherProfile' : IDL.Func([], [IDL.Opt(Teacher)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(AttendanceEntry)],
      [IDL.Vec(AttendanceRecord)],
      [],
    ),
  'registerStudent' : IDL.Func([StudentInput], [Student], []),
  'sendParentNotification' : IDL.Func(
      [IDL.Text, IDL.Text],
      [SendNotificationResult],
      [],
    ),
  'updateClass' : IDL.Func([IDL.Text, ClassInput], [Class], []),
  'updateStudent' : IDL.Func([IDL.Text, StudentInput], [Student], []),
  'updateTeacherProfile' : IDL.Func([TeacherInput], [Teacher], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClassInput = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
  });
  const Class = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'section' : IDL.Text,
    'teacherId' : IDL.Principal,
  });
  const TeacherInput = IDL.Record({
    'school' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : IDL.Principal,
    'school' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const AttendanceStatus = IDL.Variant({
    'Present' : IDL.Null,
    'Absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : AttendanceStatus,
    'studentId' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'classId' : IDL.Text,
    'markedBy' : IDL.Principal,
  });
  const DailyClassStat = IDL.Record({
    'date' : IDL.Text,
    'presentCount' : IDL.Nat,
    'attendancePercent' : IDL.Float64,
    'absentCount' : IDL.Nat,
  });
  const ClassReport = IDL.Record({
    'endDate' : IDL.Text,
    'classId' : IDL.Text,
    'dailyStats' : IDL.Vec(DailyClassStat),
    'startDate' : IDL.Text,
  });
  const StudentReport = IDL.Record({
    'studentId' : IDL.Text,
    'endDate' : IDL.Text,
    'daysAbsent' : IDL.Nat,
    'daysPresent' : IDL.Nat,
    'attendancePercent' : IDL.Float64,
    'startDate' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Text,
    'parentEmail' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'classId' : IDL.Text,
    'rollNumber' : IDL.Text,
  });
  const WeeklyTrendPoint = IDL.Record({
    'overallPercent' : IDL.Float64,
    'date' : IDL.Text,
  });
  const RecentAbsence = IDL.Record({
    'studentId' : IDL.Text,
    'studentName' : IDL.Text,
    'date' : IDL.Text,
    'classId' : IDL.Text,
    'className' : IDL.Text,
  });
  const ClassAttendanceStat = IDL.Record({
    'totalStudents' : IDL.Nat,
    'classId' : IDL.Text,
    'attendancePercent' : IDL.Float64,
    'className' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalStudents' : IDL.Nat,
    'weeklyTrend' : IDL.Vec(WeeklyTrendPoint),
    'recentAbsences' : IDL.Vec(RecentAbsence),
    'todayClassStats' : IDL.Vec(ClassAttendanceStat),
  });
  const NotificationLog = IDL.Record({
    'id' : IDL.Text,
    'parentEmail' : IDL.Text,
    'studentId' : IDL.Text,
    'sentAt' : IDL.Int,
    'sentBy' : IDL.Principal,
    'message' : IDL.Text,
  });
  const AttendanceEntry = IDL.Record({
    'status' : AttendanceStatus,
    'studentId' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
  });
  const StudentInput = IDL.Record({
    'parentEmail' : IDL.Text,
    'name' : IDL.Text,
    'classId' : IDL.Text,
    'rollNumber' : IDL.Text,
  });
  const SendNotificationResult = IDL.Record({
    'logged' : IDL.Bool,
    'emailSent' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClass' : IDL.Func([ClassInput], [Class], []),
    'createTeacherProfile' : IDL.Func([TeacherInput], [Teacher], []),
    'deleteClass' : IDL.Func([IDL.Text], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'editAttendanceRecord' : IDL.Func(
        [IDL.Text, AttendanceStatus, IDL.Opt(IDL.Text)],
        [AttendanceRecord],
        [],
      ),
    'generateClassReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ClassReport],
        ['query'],
      ),
    'generateStudentReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [StudentReport],
        ['query'],
      ),
    'getAttendanceByClassAndDate' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func([IDL.Text], [IDL.Opt(Class)], ['query']),
    'getClassStudents' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMyClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getNotificationLog' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NotificationLog)],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'getStudentAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getTeacherProfile' : IDL.Func([], [IDL.Opt(Teacher)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(AttendanceEntry)],
        [IDL.Vec(AttendanceRecord)],
        [],
      ),
    'registerStudent' : IDL.Func([StudentInput], [Student], []),
    'sendParentNotification' : IDL.Func(
        [IDL.Text, IDL.Text],
        [SendNotificationResult],
        [],
      ),
    'updateClass' : IDL.Func([IDL.Text, ClassInput], [Class], []),
    'updateStudent' : IDL.Func([IDL.Text, StudentInput], [Student], []),
    'updateTeacherProfile' : IDL.Func([TeacherInput], [Teacher], []),
  });
};

export const init = ({ IDL }) => { return []; };