/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CourseInput {
    difficultyLevel: string;
    title: string;
    thumbnailUrl: string;
    tags: Array<string>;
    description: string;
    durationMinutes: bigint;
    category: string;
    price: bigint;
    instructorName: string;
}
export interface Course {
    id: bigint;
    difficultyLevel: string;
    title: string;
    thumbnailUrl: string;
    tags: Array<string>;
    description: string;
    lessonIds: Array<bigint>;
    durationMinutes: bigint;
    category: string;
    price: bigint;
    instructorName: string;
}
export type Time = bigint;
export interface Lesson {
    id: bigint;
    title: string;
    description: string;
    durationMinutes: bigint;
    videoUrl: string;
    courseId: bigint;
    orderIndex: bigint;
}
export interface EnrollmentInput {
    courseId: bigint;
}
export interface QuizQuestion {
    answerOptions: Array<string>;
    questionText: string;
    correctAnswerIndex: bigint;
}
export interface LessonInput {
    title: string;
    description: string;
    durationMinutes: bigint;
    videoUrl: string;
    courseId: bigint;
    orderIndex: bigint;
}
export interface Enrollment {
    completionPercentage: bigint;
    completedLessons: Array<bigint>;
    student: Principal;
    enrollmentDate: Time;
    courseId: bigint;
}
export interface QuizSubmissionInput {
    answers: Array<bigint>;
    courseId: bigint;
}
export interface Review {
    reviewText: string;
    student: Principal;
    rating: bigint;
    courseId: bigint;
}
export interface QuizSubmission {
    answers: Array<bigint>;
    score: bigint;
    student: Principal;
    courseId: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addQuizQuestions(courseId: bigint, questions: Array<QuizQuestion>): Promise<void>;
    addReview(courseId: bigint, rating: bigint, reviewText: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCourse(input: CourseInput): Promise<bigint>;
    createLesson(input: LessonInput): Promise<bigint>;
    enrollInCourse(input: EnrollmentInput): Promise<void>;
    getAllCourses(): Promise<Array<Course>>;
    getCallerUserRole(): Promise<UserRole>;
    getCourse(courseId: bigint): Promise<Course>;
    getCourseReviews(courseId: bigint): Promise<Array<Review>>;
    getCoursesByCategory(category: string): Promise<Array<Course>>;
    getCoursesSortedByPrice(): Promise<Array<Course>>;
    getLesson(lessonId: bigint): Promise<Lesson>;
    getMyEnrollments(): Promise<Array<Enrollment>>;
    getMyQuizResults(): Promise<Array<QuizSubmission>>;
    isCallerAdmin(): Promise<boolean>;
    markLessonComplete(courseId: bigint, lessonId: bigint): Promise<void>;
    submitQuiz(input: QuizSubmissionInput): Promise<bigint>;
}
import type { UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addQuizQuestions(arg0: bigint, arg1: Array<QuizQuestion>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuizQuestions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuizQuestions(arg0, arg1);
            return result;
        }
    }
    async addReview(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCourse(arg0: CourseInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0);
            return result;
        }
    }
    async createLesson(arg0: LessonInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLesson(arg0);
            return result;
        }
    }
    async enrollInCourse(arg0: EnrollmentInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollInCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollInCourse(arg0);
            return result;
        }
    }
    async getAllCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCourses();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: bigint): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return result;
        }
    }
    async getCourseReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseReviews(arg0);
            return result;
        }
    }
    async getCoursesByCategory(arg0: string): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesByCategory(arg0);
            return result;
        }
    }
    async getCoursesSortedByPrice(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoursesSortedByPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoursesSortedByPrice();
            return result;
        }
    }
    async getLesson(arg0: bigint): Promise<Lesson> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return result;
        }
    }
    async getMyEnrollments(): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEnrollments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEnrollments();
            return result;
        }
    }
    async getMyQuizResults(): Promise<Array<QuizSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuizResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuizResults();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markLessonComplete(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markLessonComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markLessonComplete(arg0, arg1);
            return result;
        }
    }
    async submitQuiz(arg0: QuizSubmissionInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuiz(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuiz(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
